//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Net;
using System.Net.Sockets;
namespace DeadAlbatross.Client
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://DeadAlbatross.Server", ConfigurationName = "Server")]
    public interface Server
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://DeadAlbatross.Server/Server/ListShares", ReplyAction = "http://DeadAlbatross.Server/Server/ListSharesResponse")]
        DeadAlbatross.Commons.Share[] ListShares();

        [System.ServiceModel.OperationContractAttribute(Action = "http://DeadAlbatross.Server/Server/ReportShares", ReplyAction = "http://DeadAlbatross.Server/Server/ReportSharesResponse")]
        void ReportShares(DeadAlbatross.Commons.Share[] shares);

        [System.ServiceModel.OperationContractAttribute(Action = "http://DeadAlbatross.Server/Server/RequestDownload", ReplyAction = "http://DeadAlbatross.Server/Server/RequestDownloadResponse")]
        string[] RequestDownload(string hash);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServerChannel : Server, System.ServiceModel.IClientChannel
    {
    }

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServerClient : System.ServiceModel.ClientBase<Server>, Server
    {

        public ServerClient()
        {
        }

        public ServerClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ServerClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public DeadAlbatross.Commons.Share[] ListShares()
        {
            return base.Channel.ListShares();
        }

        public void ReportShares(DeadAlbatross.Commons.Share[] shares)
        {
            base.Channel.ReportShares(shares);
        }

        public string[] RequestDownload(string hash)
        {
            return base.Channel.RequestDownload(hash);
        }
    }
}